try {
    throw Error('This will throw a error!')
  } catch (e){
    console.log(e)
}